split:
  test_size: 0.2
  random_state: 42

train:
  model_type: "RandomForest"
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42

data:
  input_file: "data/iris_dataset.csv"
  
model:
  output_path: "model/model.pkl"
  
metrics:
  output_path: "metrics/eval.json"